### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by nikipore** [nikipore/stompest#20]
Python 3 support would really be awesome, but there are some caveats:

1. I am in a pure Python 2.7 world at work, so (a) Python 2.7 backward compatibility is a must and (b) I would not feel able to maintain a production-level stability. The latter means: contributions are welcome!
2. It would probably make sense to switch from Twisted to asyncio/Tulip.

**Comment by tobgu** [comment]
Hi!

I see there are a bunch of commits that introduce python 3 support that have not yet been merged to master. Are there any plans on including them and releasing a python 3 compatible version soon? Would be much appreciated!

**Comment by nikipore** [comment]
This repository has only one branch `master`, and there are no pull requests which would introduce Python 3 support.

The situation as described above remains unchanged. I am not going to invest my own time into this issue, save review and testing, of course. Since Twisted is Python 3 compatible now, the changes should be minimal and straightforward, though, so I am inviting you and everyone else to help out with contributions.

**Comment by tobgu** [comment]
OK, I'll contact the author of those commits to see if he could make a PR so that it can be included in master and released.

**Comment by hydratk** [comment]
I created PR 34 which contains modifications to run stompest.core on Python 3.

**Comment by nikipore** [comment]
Awesome, thank you very much! In hindsight it doesn't look like sorcery. I'll make a review; when you have made the amendments, I'll run the tests.

**Comment by hydratk** [comment]
Hi, 
thank you for comments and advises.
Modified version is submitted, tests passed in my environment with ActiveMQ

**Comment by nikipore** [comment]
[I just pushed my amendments.](https://github.com/nikipore/stompest/commit/2c897ca95b614d6e6bbf2c50afe479f26fdae8b9) All tests pass; I changed some of them because I tried to make the API as harmonious between Python 2 and 3 as possible. Please have a look and comment before I go on to amend the docs and write release notes.

**Comment by hydratk** [comment]
Hi,
I looked at your changes and they are fine, thank you.

**Comment by nikipore** [comment]
Included in release 2.2.0 and uploaded to PyPI. Have fun and please let me know if anything is broken.
