### ISSUE TITLE
Concurrent connection attempts are impossible

### ISSUE THREAD

**Issue by mhsmith** [nikipore/stompest#28]
Someone asked you about it [here](https://groups.google.com/forum/#!topic/stompest/1JdCadsnznc), and you said:

> you would never want to send two CONNECT frames over the same wire-level connection, which is why there is an @exclusive wrapper around the connect() method. If you want to run more than one STOMP session, then you'll have to instantiate a dedicated async.Stomp connection for each STOMP session

But the @exclusive wrapper doesn't pay any attention to what connection it's being called on. It prevents all concurrent calls to the connect method, in all objects.

**Comment by nikipore** [comment]
Just checked it, and you're right. This is a leftover feature from a time when there was no `StompSession` object attached to the `async.Stomp` connection and can probably be removed safely:

1. remove the `@exclusive` wrapper, its implementation in `async.utils` and corresponding unit test cases (if any).
2. check whether there are test cases checking for the `StompAlreadyRunningError` (coming from the `@exclusive`which should be a `StompProtocolError` (coming from the `StompSession`) now and redefine them accordingly.

I am far too busy to dive into this myself over the next few weeks if not months, but I would certainly lend myself for a code review, a final test and a new PyPI package.

**Comment by nikipore** [comment]
Fixed in 2.2.0.
