### ISSUE TITLE
How to config exclusive=true ?

### ISSUE THREAD

**Issue by wcc526** [nikipore/stompest#33]
http://activemq.apache.org/exclusive-consumer.html

java code is

   queue = new ActiveMQQueue("TEST.QUEUE?consumer.exclusive=true");
   consumer = session.createConsumer(queue);
I have try to config uri

failover:(tcp://xxxx:61613,tcp://xxx)?exclusive=true,randomize=false,maxReconnectDelay=30000

there is a errror:

[invalid options: 'exclusize']
Exception AttributeError: "'ActiveMQConsumer' object has no attribute 'client'" in <bound method

**Comment by nikipore** [comment]
What exactly is your question or problem? Please post non-working Python (not Java) code.

**Comment by wcc526** [comment]
from stompest.config import StompConfig
from stompest.protocol import StompSpec
from stompest.sync import Stomp
from stompest.protocol import StompParser
class ActiveMQConsumer(object):
    def __init__(self, dest, uri, login, passcode, message_type=None):
        self.dest = dest
        self.config = StompConfig(uri=uri, login=login, passcode=passcode,version='1.1')
        self.message_type = message_type
        self.client = Stomp(self.config)
        self.client.connect()

        headers = {
            'ack': 'auto',
            'id': 'required-for-STOMP-1.1',
            'exclusive':'true'
        }
        if message_type == 'MapMessage':
            headers['transformation'] = 'jms-map-json'
        self.client.subscribe(self.dest, headers)

    def __map_json_to_dict(self, body):
        ret_dict = {}
        body_dict = json.loads(body)
        for entry in body_dict['map']['entry']:
            key = entry['string'][0]
            value = entry['string'][1]
            ret_dict[key] = value
        return ret_dict

    def recv(self):
        if self.client.canRead(1):
            self.frame = self.client.receiveFrame()
            # self.client.ack(self.frame)
            if self.message_type == 'MapMessage':
                body = self.__map_json_to_dict(self.frame.body)
            else:
                body = json.loads(self.frame.body)
            return body
        else:
            return None

    def ack(self):
        self.client.ack(self.frame)

    def __del__(self):
        self.client.disconnect()

**Comment by wcc526** [comment]
headers = {
            'ack': 'auto',
            'id': 'required-for-STOMP-1.1',
            'exclusive':'true'
        }

 It does not work.

**Comment by nikipore** [comment]
Well, `exclusive` is no supported option of the `stompest` failover protocol.
