### ISSUE TITLE
Messages not recieving after queue is idle for some time

### ISSUE THREAD

**Issue by vikvns** [nikipore/stompest#35]
I am facing a issue with ActiveMQ. The consumer is not receiving messages, even though it's connected to ActiveMQ queue. This starts happening when queue is idle for some time(~ 3 hours).
I am using synchronous client.

**Comment by nikipore** [comment]
Sounds like, well, an ActiveMQ issue. The synchronous client really is a very thin wrapper around a standard Python network socket. Did you ask for help on the ActiveMQ side?
